data class Comment(
    val ownerId: Int,
    val postId: Int,
    val fromGroup: Int,
    val message: String,
    val replyToComment: Int,
    val attachments: Array<Attachment>?,
    val stickerId: Int,
    val guid: String)
